# 2022-07-14
## 프로그래머가 알아야 할 알고리듬 40: 2장 알고리듬에 사용되는 자료구조 학습 

In [1]:
# filter 함수와 람다 함수 - 데이터 필터링 
list(filter(lambda x : x > 100, [-5, 200, 300, -10, 10, 1000]))

[200, 300, 1000]

In [11]:
# 맵 함수 활용하기 - 데이터 변환
list(map(lambda x: x**3, [1,2,3,4,5]))

[1, 8, 27, 64, 125]

In [4]:
# 리듀스 함수 활용해서 데이터 집계하기 - 데이터 집계 
from functools import reduce 
reduce(lambda x, y: x + y, [1,2,3,4,5])

15

In [6]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [16]:
import pandas as pd 
df = pd.DataFrame([
    ['1', 'jack', 32, True], 
    ['2', 'simon', 33, True], 
    ['3', 'afs', 44, False]
], columns = ['id', 'name', 'age', 'boo']) ; df 

id   name  age    boo
0  1   jack   32   True
1  2  simon   33   True
2  3    afs   44  False

In [21]:
# 데이터프레임 조건에 따른 필터링
df[(df.age> 30) & (df.boo != True)]

id name  age    boo
2  3  afs   44  False

In [24]:
# 행렬 전치 
A = np.array([
    [11,21,31],
    [12,22,32],
    [13,23,33]
])
A

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [25]:
A.T

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [30]:
# 열벡터 
vector1 = np.array([1,2,3,4,5])
print(vector1)

vector2 = np.array([
    [1], 
    [2], 
    [3], 
    [4],
    [5]
])
print(vector2)

[1 2 3 4 5]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [32]:
# 스택 구현 
class Stack : 
    def __init__(self) : 
        self.items = [] # 리스트 이용해 스택 구현 
    
    # 스택에 삽입
    def push(self, x) : 
        self.items.append(x)
    
    # 스택이 비어있는지 확인
    def isEmpty(self) : 
        return len(self.items) == 0 
    
    # 스택 맨 위에서 항목 제거 
    def pop(self) : 
        deleted = self.items.pop()
        return deleted 
    
    # 스택 맨 위 항목 확인 
    def peek(self) : 
        return self.items[-1]
    
    # 스택안에 요소 몇개 들었는지 확인 
    def size(self) : 
        return len(self.items)

In [37]:
stack = Stack() 

# 스택이 비어있는지 확인 
print(f'스택이 비어있는지 확인: {stack.isEmpty()}')

# 스택에 요소 추가 
stack.push('red')
stack.push('green')
stack.push('blue')
stack.push('yellow')

# 스택에서 최근에 입력한 요소 꺼내오기 
stack.pop() 

스택이 비어있는지 확인: True


'yellow'

In [38]:
# 스택 출력 
stack.items

['red', 'green', 'blue']

In [39]:
# 스택이 비어있는지 확인 
stack.isEmpty()

False

In [40]:
# 스택에 들어있는 요소 개수 확인 
stack.size()

3

In [41]:
# 스택 맨 위에 요소 확인 
stack.peek()

'blue'

In [4]:
# 큐 구현 
class Queue : 
    # 파이썬 리스트로 큐 구현 
    def __init__(self) : 
        self.items = [] 

    # 큐 후단에 항목 추가 
    def enqueue(self, item) : 
        self.items.append(item)
    
    # 큐 전단에서 항목 제거 
    def dequeue(self) : 
        return self.items.pop(0)
    
    # 큐 안에 들어있는 요소들 갯수 반환
    def size(self) : 
        return len(self.items)

    # 큐가 비어있는지 여부 확인 
    def isEmpty(self) : 
        return self.items == []

In [6]:
# 큐 객체 생성 및 큐에 요소 삽입 
queue = Queue() 
queue.enqueue('red')
queue.enqueue('green')
queue.enqueue('blue')
queue.enqueue('yellow')

# 큐 사이즈 출력 
print(queue.size())

4


In [7]:
queue.items

['red', 'green', 'blue', 'yellow']

In [8]:
print(queue.dequeue())
print(queue.dequeue())

red
green
