In [3]:
# 딕셔너리로 데이터프레임 생성하기 
hd = pd.DataFrame({
    '해운대구' : ['좌동','우동','중동'],
    '기장군' : ['정관읍','일광면','동리'],
    '광안리' : ['1동','2동','3동']
},
index=[1,2,3])
hd

해운대구  기장군 광안리
1   좌동  정관읍  1동
2   우동  일광면  2동
3   중동   동리  3동

In [12]:
#행렬로 데이터프레임 생성하기
pd.DataFrame(np.array([['좌동','정관읍','1동'],#행렬, ndarray객체 
                      ['우동','일광면','2동'],
                      ['중동','동리','3동']]),
            columns=['해운대구','기장군','광안리'],
            index=[1,2,3])

해운대구  기장군 광안리
1   좌동  정관읍  1동
2   우동  일광면  2동
3   중동   동리  3동

In [13]:
#2차원 리스트로 데이터프레임 생성하기 
pd.DataFrame([['좌동','정관읍','1동'],
             ['우동','일광면','2동'],
             ['중동','동리','3동']],
            columns=['해운대구','기장군','광안리'],
            index=[1,2,3])

해운대구  기장군 광안리
1   좌동  정관읍  1동
2   우동  일광면  2동
3   중동   동리  3동

In [15]:
df = pd.DataFrame([['사자','돌부처','분수대','회전목마'],
                  ['호랑이','십자가','호수','회전 컵'],
                  ['토끼','안데르센 동상','타오르는 촛대','롤러코스터'],
                  ['원숭이','손오공 동상','소나무 조각상','워터캠프']],
                 index=pd.MultiIndex.from_tuples([['바람','1구역'],
                                                 ['바람','2구역'],
                                                 ['햇님','3구역'],
                                                 ['별님','4구역']]),
                 columns=[['생물','무생물','무생물','무생물'],
                         ['관람 가능 동물','조형물','시설물','놀이기구']])
df

생물      무생물                
       관람 가능 동물      조형물      시설물   놀이기구
바람 1구역       사자      돌부처      분수대   회전목마
   2구역      호랑이      십자가       호수   회전 컵
햇님 3구역       토끼  안데르센 동상  타오르는 촛대  롤러코스터
별님 4구역      원숭이   손오공 동상  소나무 조각상   워터캠프

In [17]:
df.drop_duplicates()
#깔끔한 데이터 공리 : 
#1. 칼럼에는 변수만, 변수에는 유니크한 값 하나만 들어갈 것. 
#2. row에는 유니크한 관측치 하나만 들어갈 것. 
#3. 하나의 표에는 하나의 관측단위만 들어갈 것. 

생물      무생물                
       관람 가능 동물      조형물      시설물   놀이기구
바람 1구역       사자      돌부처      분수대   회전목마
   2구역      호랑이      십자가       호수   회전 컵
햇님 3구역       토끼  안데르센 동상  타오르는 촛대  롤러코스터
별님 4구역      원숭이   손오공 동상  소나무 조각상   워터캠프

# 1번 공리 안 맞음 --> 칼럼에 있는 여러 변수 값들 내리기 & 인덱스에 변수 값들 들어가 있는 것 제거해야 함. 
# 2번 공리 맞음
# 3번 공리 맞음

In [23]:
# 1. 인덱스에 들어가 있는 변숫값들 제거 
df = df.reset_index(drop=False).rename(mapper={'level_0':'공원이름'}, axis=1).rename(mapper={'level_1':'구역이름'},axis=1)

In [24]:
df

공원이름 구역이름       생물      무생물                
            관람 가능 동물      조형물      시설물   놀이기구
0   바람  1구역       사자      돌부처      분수대   회전목마
1   바람  2구역      호랑이      십자가       호수   회전 컵
2   햇님  3구역       토끼  안데르센 동상  타오르는 촛대  롤러코스터
3   별님  4구역      원숭이   손오공 동상  소나무 조각상   워터캠프

In [27]:
#2. 칼럼에 있는 여러 변숫값들 내리자. 
df = df.melt(id_vars=['공원이름','구역이름'],var_name=['카테고리 구분','세부 카테고리 구분'],value_name='관람대상들')

In [36]:
df.sort_values(by=['구역이름','카테고리 구분'], axis=0, inplace=True)

In [39]:
df.reset_index(drop=True, inplace=True)

In [41]:
df #깔끔한 데이터 

공원이름 구역이름 카테고리 구분 세부 카테고리 구분    관람대상들
0    바람  1구역     무생물        조형물      돌부처
1    바람  1구역     무생물        시설물      분수대
2    바람  1구역     무생물       놀이기구     회전목마
3    바람  1구역      생물   관람 가능 동물       사자
4    바람  2구역     무생물        조형물      십자가
5    바람  2구역     무생물        시설물       호수
6    바람  2구역     무생물       놀이기구     회전 컵
7    바람  2구역      생물   관람 가능 동물      호랑이
8    햇님  3구역     무생물        조형물  안데르센 동상
9    햇님  3구역     무생물        시설물  타오르는 촛대
10   햇님  3구역     무생물       놀이기구    롤러코스터
11   햇님  3구역      생물   관람 가능 동물       토끼
12   별님  4구역     무생물        조형물   손오공 동상
13   별님  4구역     무생물        시설물  소나무 조각상
14   별님  4구역     무생물       놀이기구     워터캠프
15   별님  4구역      생물   관람 가능 동물      원숭이

In [48]:
df.pivot(index=['공원이름','구역이름'],columns=['카테고리 구분','세부 카테고리 구분'],values='관람대상들').sort_values(by=['구역이름'],inplace=True)

In [51]:
df.head()

공원이름 구역이름 카테고리 구분 세부 카테고리 구분 관람대상들
0   바람  1구역     무생물        조형물   돌부처
1   바람  1구역     무생물        시설물   분수대
2   바람  1구역     무생물       놀이기구  회전목마
3   바람  1구역      생물   관람 가능 동물    사자
4   바람  2구역     무생물        조형물   십자가

In [53]:
df_add = pd.DataFrame(np.array([['토성','8구역','생물','동물','코끼리']]),
            columns=['공원이름','구역이름','카테고리 구분','세부 카테고리 구분','관람대상들'])
df_add

공원이름 구역이름 카테고리 구분 세부 카테고리 구분 관람대상들
0   토성  8구역      생물         동물   코끼리

In [55]:
df_c = pd.concat([df,df_add],axis=0)

In [59]:
df_c.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 17 entries, 0 to 0
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   공원이름        17 non-null     object
 1   구역이름        17 non-null     object
 2   카테고리 구분     17 non-null     object
 3   세부 카테고리 구분  17 non-null     object
 4   관람대상들       17 non-null     object
dtypes: object(5)
memory usage: 816.0+ bytes


In [108]:
df_add2 = pd.DataFrame(np.array([['아이언맨','ㅎㅇ'],
                      ['배트맨','ㄹㄹ'],
                      ['슈퍼맨','ㅁㅁ'],
                      ['원더우먼','ㅌㅌ'],
                      ['캡틴','ㄹㄹ'],
                      ['블랙위도우','ㅁ'],
                      ['블랙팬서','ㅌ'],
                      ['비전','2'],
                      ['완다','ㄹㄹ'],
                      ['쉴드','ㄴㅇㄹ'],
                      ['닉 퓨리','ㅁㄹㅁ'],
                      ['캡틴 마블','ㄹㄹ'],
                      ['스크럴','ㅁㄹㅁ'],
                      ['슈리','ㅉ']]),
            columns=['xx','히어로물'])
df_add2

xx 히어로물
0    아이언맨   ㅎㅇ
1     배트맨   ㄹㄹ
2     슈퍼맨   ㅁㅁ
3    원더우먼   ㅌㅌ
4      캡틴   ㄹㄹ
5   블랙위도우    ㅁ
6    블랙팬서    ㅌ
7      비전    2
8      완다   ㄹㄹ
9      쉴드  ㄴㅇㄹ
10   닉 퓨리  ㅁㄹㅁ
11  캡틴 마블   ㄹㄹ
12    스크럴  ㅁㄹㅁ
13     슈리    ㅉ

In [109]:
pd.concat([df_c, df_add2],axis=1, join='inner')

공원이름 구역이름 카테고리 구분 세부 카테고리 구분    관람대상들     xx 히어로물
0    바람  1구역     무생물        조형물      돌부처   아이언맨   ㅎㅇ
1    바람  1구역     무생물        시설물      분수대    배트맨   ㄹㄹ
2    바람  1구역     무생물       놀이기구     회전목마    슈퍼맨   ㅁㅁ
3    바람  1구역      생물   관람 가능 동물       사자   원더우먼   ㅌㅌ
4    바람  2구역     무생물        조형물      십자가     캡틴   ㄹㄹ
5    바람  2구역     무생물        시설물       호수  블랙위도우    ㅁ
6    바람  2구역     무생물       놀이기구     회전 컵   블랙팬서    ㅌ
9    햇님  3구역     무생물        시설물  타오르는 촛대     쉴드  ㄴㅇㄹ
10   햇님  3구역     무생물       놀이기구    롤러코스터   닉 퓨리  ㅁㄹㅁ
11   햇님  3구역      생물   관람 가능 동물       토끼  캡틴 마블   ㄹㄹ
12   별님  4구역     무생물        조형물   손오공 동상    스크럴  ㅁㄹㅁ
13   별님  4구역     무생물        시설물  소나무 조각상     슈리    ㅉ

In [92]:
df_c.reset_index(drop=True, inplace=True)

In [105]:
df_c.drop([7,8],axis=0,inplace=True )

In [112]:
df = pd.concat([df_c, df_add2],axis=1,join='inner')

In [113]:
df

공원이름 구역이름 카테고리 구분 세부 카테고리 구분    관람대상들     xx 히어로물
0    바람  1구역     무생물        조형물      돌부처   아이언맨   ㅎㅇ
1    바람  1구역     무생물        시설물      분수대    배트맨   ㄹㄹ
2    바람  1구역     무생물       놀이기구     회전목마    슈퍼맨   ㅁㅁ
3    바람  1구역      생물   관람 가능 동물       사자   원더우먼   ㅌㅌ
4    바람  2구역     무생물        조형물      십자가     캡틴   ㄹㄹ
5    바람  2구역     무생물        시설물       호수  블랙위도우    ㅁ
6    바람  2구역     무생물       놀이기구     회전 컵   블랙팬서    ㅌ
9    햇님  3구역     무생물        시설물  타오르는 촛대     쉴드  ㄴㅇㄹ
10   햇님  3구역     무생물       놀이기구    롤러코스터   닉 퓨리  ㅁㄹㅁ
11   햇님  3구역      생물   관람 가능 동물       토끼  캡틴 마블   ㄹㄹ
12   별님  4구역     무생물        조형물   손오공 동상    스크럴  ㅁㄹㅁ
13   별님  4구역     무생물        시설물  소나무 조각상     슈리    ㅉ

# 1. df[w].value_counts() : 각 변수의 유니크한 값value들 갯수를 세어준다. 

In [121]:
# df[w].value_counts() : 각 변수의 유니크한 값value들 갯수를 세어준다. 
df[['구역이름','공원이름']].value_counts(ascending=True)

구역이름  공원이름
4구역   별님      2
2구역   바람      3
3구역   햇님      3
1구역   바람      4
dtype: int64

In [120]:
df.value_counts(['공원이름','구역이름'],ascending=True)

공원이름  구역이름
별님    4구역     2
바람    2구역     3
햇님    3구역     3
바람    1구역     4
dtype: int64

In [123]:
#normalization : normalize=True 이면 빈도값 대신에 비율로 나타내준다. 
df.value_counts(['공원이름','구역이름'],ascending=True, normalize=True)

공원이름  구역이름
별님    4구역     0.166667
바람    2구역     0.250000
햇님    3구역     0.250000
바람    1구역     0.333333
dtype: float64

In [124]:
df[['공원이름','구역이름']].value_counts(ascending=True, normalize=True)

공원이름  구역이름
별님    4구역     0.166667
바람    2구역     0.250000
햇님    3구역     0.250000
바람    1구역     0.333333
dtype: float64

In [128]:
df[['공원이름','구역이름']].value_counts(ascending=True, normalize=False, sort=True)

공원이름  구역이름
별님    4구역     2
바람    2구역     3
햇님    3구역     3
바람    1구역     4
dtype: int64

# 2. len(df) : df에 있는 row 수를 세어준다. 

In [134]:
# 2. len(df) : df에 있는 row 수를 세어준다. 
len(df[['공원이름','구역이름']])

12

In [138]:
# 3. df['w'].nunique() : 칼럼 값 중 유니크한 값들 갯수 세어준다. 내가 만든 예의 경우 바람, 별님, 햇님 3개 
df['공원이름'].nunique()

3

In [143]:
df.describe() #기초통계량 정보 보여준다. 평균,표준편차,최빈값,사분위수 등 중심위치 및 산포측도 정보 준다. 

공원이름 구역이름 카테고리 구분 세부 카테고리 구분 관람대상들   xx 히어로물
count    12   12      12         12    12   12   12
unique    3    4       2          4    12   12    9
top      바람  1구역     무생물        시설물   돌부처  배트맨   ㄹㄹ
freq      7    4      10          4     1    1    3

In [147]:
# summarize data 하기 위한 각종 메서드 쓰면, 결과값은 시리즈, 정수, 문자열 등으로 반환된다. 
df['공원이름'].sum()

'바람바람바람바람바람바람바람햇님햇님햇님별님별님'

In [148]:
df['공원이름'].min()

'바람'

In [150]:
df['공원이름'].count() #변수 값 중에 null이 아닌 것들 갯수를 센다. 

12

In [156]:
df_test = pd.DataFrame([[1,2,3],
             [4,5,6],
             [4,59,1],
                       [None,1,1]])
df_test

0   1  2
0  1.0   2  3
1  4.0   5  6
2  4.0  59  1
3  NaN   1  1

In [157]:
df_test[0].count()

3

In [163]:
df_test[0].median()

4.0

In [165]:
df_test.quantile([0.25,0.5,0.75]) #산포측도, 사분위수

0      1     2
0.25  2.5   1.75  1.00
0.50  4.0   3.50  2.00
0.75  4.0  18.50  3.75

# df.apply()

In [178]:
#각 칼럼 또는 row에 apply() 내부의 함수 적용
#raw = true 이면 func안에 ndarray 객체를 넣는다. false이면 시리즈로 넣는다.
#
df_test.apply(print,axis=1,raw=True,result_type='reduce')

[1. 2. 3.]
[4. 5. 6.]
[ 4. 59.  1.]
[nan  1.  1.]


0    None
1    None
2    None
3    None
dtype: object

In [211]:
df.apply?

# result_type은 axis=1 일때만 작동한다.
- result_type='expand' 이면, 리스트 형식으로 나온 결과값을 데이터프레임 형식으로 바꿔준다. 
- result_type='broadcast' 이면, 결과값이 리스트 형식이든, 스칼라이든 상관없이 데이터프레임 형식으로 바꿔 출력해준다. 
- result_type='reduce' 이면, 리스트 형식으로 나온 결과값을 가능한 한 데이터프레임 형식 말고 시리즈 형식으로 return해준다. 
- none이면 시리즈로 결과값을 반환한다. 만약 함수가 시리즈 형식을 반환하면 데이터프레임 형식으로 결과값 반환한다. 

- args : func에 함께 넣을 tuple을 지정해줄 수 있다. 
- kwds : func에 넣을 추가적인 keyword argument를 지정해준다. 
- 최종 결과값은 시리즈 또는 데이터프레임으로 나온다. 

In [183]:
df_test2 = pd.DataFrame([[1,2,3],
                        [4,5,6],
                        [7,8,9]])
df_test2

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [193]:
df_test2.apply(np.sqrt,axis=1,result_type='expand')

0         1         2
0  1.000000  1.414214  1.732051
1  2.000000  2.236068  2.449490
2  2.645751  2.828427  3.000000

In [196]:
df_test2.apply(np.sqrt,axis=1, result_type=None)

0         1         2
0  1.000000  1.414214  1.732051
1  2.000000  2.236068  2.449490
2  2.645751  2.828427  3.000000

In [202]:
df_test2.apply(np.sqrt,axis=1, result_type='broadcast')

0         1         2
0  1.000000  1.414214  1.732051
1  2.000000  2.236068  2.449490
2  2.645751  2.828427  3.000000

In [201]:
type(np.sqrt(df_test2.iloc[0]))

pandas.core.series.Series

In [204]:
df_test2.apply(sum, axis=1, result_type='broadcast')

0   1   2
0   6   6   6
1  15  15  15
2  24  24  24

In [210]:
df_test2.apply(sum, axis=1, result_type='reduce')

0     6
1    15
2    24
dtype: int64