In [5]:
A = np.array([[1,2,3],
         [2,3,4],
         [4,5,6]])
np.linalg.det(A) #역행렬 없는 특이행렬이다. 

0.0

In [6]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [19]:
B = np.array([[1,2,3],
             [1,1,1],
             [5,6,7]])
np.linalg.det(B) #역행렬 있다. 

8.881784197001244e-16

In [20]:
B_inv = np.linalg.inv(B) #B의 역행렬

In [25]:
b = np.array([[2],
             [2],
             [3]])
x = B_inv@b

In [30]:
x

array([[-0.21296296],
       [ 0.14814815],
       [ 0.50925926]])

In [27]:
B_inv@b - x

array([[0.],
       [0.],
       [0.]])

In [29]:
x, resid, rank, s = np.linalg.lstsq(B,b)
x

array([[-0.21296296],
       [ 0.14814815],
       [ 0.50925926]])

In [43]:
from sklearn.datasets import load_boston
boston = load_boston()

X = boston.data
Y = boston.target

A = X[:4, [0,4,5,6]] #정방행렬 A
b = Y[:4]

# A 행렬 역행렬이 존재하는가? 
np.linalg.det(A) #존재한다. 

0.2178418370180003

In [58]:
# A의 역행렬
A_inv = np.linalg.inv(A)
A_inv@b

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [51]:
w_list = list(A_inv@b)
print('1.범죄율 : %s' %w_list[0])
print('2.공기 오염도 : %s' %w_list[1])
print('3.방 개수 : %s' %w_list[2])
print('4.오래된 정도 : %s'%w_list[3])

1.범죄율 : -312.7100432703901
2.공기 오염도 : -115.1939423455492
3.방 개수 : 14.499646531804672
4.오래된 정도 : -0.11325931735032801


In [60]:
#게수행렬 & 데이터레코드
A = np.array([[1,1,0],
             [0,1,1],
             [1,1,1],
             [1,1,2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [61]:
# 실제값
b = np.array([[2],
             [2],
             [3],
             [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [69]:
# 잔차 최소화하는 x값은? 
#1. 의사역행렬 이용해서 x값 추정하기 
A_P = np.linalg.inv(A.T@A)@A.T #행렬 A의 의사역행렬
x = A_P@b

In [70]:
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [72]:
A@x #b_hat

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [75]:
A@x-b #잔차벡터 e

array([[-0.01666667],
       [ 0.        ],
       [ 0.03333333],
       [-0.01666667]])

In [78]:
# 2. lstsq() 최소자승법으로 미지수 해 구하기 
x, resid, rank, s = np.linalg.lstsq(A, b)
x #잔차 크기 최소화하는 미지수의 해 

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [82]:
#잔차 크기 : 잔차제곱합
resid, np.linalg.norm(A@x-b)**2 #둘다 잔차의 크기 : 잔차제곱합을 나타낸다. 

(array([0.00166667]), 0.0016666666666666846)

In [104]:
#2.4.6 연습문제 복습 
from sklearn.datasets import load_boston
boston = load_boston()

X = boston.data #전체 데이터셋 (계수행렬)
y = boston.target #실제값

In [110]:
# 목표 : 가중치 w로 구성된 미지수벡터 구하기 
# 1. 최소자승법의 해 - 의사역행렬 이용해서 구하기 
X_inv = np.linalg.inv(X.T@X)

In [111]:
X = (X_inv@X.T)@y

In [112]:
X
w_list = list(X)
print('1.범죄율 %s' %w_list[0])
print('2.비소매상업지역 면절 비율 : %s'%w_list[1])
print('3.일산화질소 농도 : %s' %w_list[2])
print('4.주택 당 방 수 : %s' %w_list[3])
print('5.인구 중 하위 계층 비율 : %s' %w_list[4])
print('6.인구 중 흑인 비율 : %s' %w_list[5])
print('7.학생/교사 비율 : %s' %w_list[6])
print('8.25,000 평방피트 초과 거주지역 비율 : %s' %w_list[7])
print('9.찰스강 경계에 위치한 경우는 1, 아니면 0 %s'%w_list[8])
print('10.1940년 이전에 건축된 주택의 비율 : %s' %w_list[9])
print('11.방사형 고속도로까지의 거리 : %s' %w_list[10])
print('12.보스톤 직업센터 5곳까지의 가중평균 거리 : %s' %w_list[11])
print('13.재산세율 : %s' %w_list[12])

1.범죄율 -0.09289651702763603
2.비소매상업지역 면절 비율 : 0.04871495518298141
3.일산화질소 농도 : -0.004059979575099154
4.주택 당 방 수 : 2.8539988199897244
5.인구 중 하위 계층 비율 : -2.868436370410512
6.인구 중 흑인 비율 : 5.928147779053034
7.학생/교사 비율 : -0.007269334576063238
8.25,000 평방피트 초과 거주지역 비율 : -0.9685141573951589
9.찰스강 경계에 위치한 경우는 1, 아니면 0 0.17115112829438467
10.1940년 이전에 건축된 주택의 비율 : -0.009396215397157747
11.방사형 고속도로까지의 거리 : -0.3921909262950018
12.보스톤 직업센터 5곳까지의 가중평균 거리 : 0.014905610228203357
13.재산세율 : -0.4163044707374216


In [108]:
#2. 최소자승법의 해 : 최소자승법 메서드 lstsq()이용해서 미지수 해 찾기 (가중치)
x, resid, rank, s = np.linalg.lstsq(X, y)
x, resid#잔차제곱합 최소로 만드는 미지수 해 x들 벡터 / 잔차제곱합(= 잔차크기)

(array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
        -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
         1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
        -4.16304471e-01]),
 array([12228.04626104]))