$A*v=\lambda*v$
- 위 식 성립하는 lambda와 v벡터는 각각 행렬 A의 고윳값, 고유벡터다. 

In [3]:
#연습문제 3.3.1
B = np.array([[2,3],
             [2,1]])

lambda1 = 4
v1 = np.array([[3/np.sqrt(13)],
              [2/np.sqrt(13)]])

lambda2 = -1
v2 = np.array([[-1/np.sqrt(2)],
              [1/np.sqrt(2)]])

In [4]:
B@v1 == lambda1*v1

array([[ True],
       [ True]])

In [5]:
B@v2 == lambda2*v2

array([[ True],
       [ True]])

# 넘파이 사용한 고유분해 
$A*v = \lambda*v$

In [14]:
A = np.array([[1,-2],
             [2,-3]])
w1, v1 = np.linalg.eig(A) #고유분해 메서드 eig()

print(w1) #각 요소가 고윳값
print(v1) #각 열이 고유벡터

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [17]:
B = np.array([[2,3],
             [2,1]])
w2, v2 = np.linalg.eig(B) #고유분해 메서드

print(w2) #고윳값
print(v2) #고유벡터(열)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [20]:
C = np.array([[0,-1],
             [1,0]])
w3, v3 = np.linalg.eig(C)

print(w3) #복소수 고윳값
print(v3) #복소수로 구성된 고유벡터

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [25]:
# 3.3.5 연습문제 
#1. 
B = np.array([[2,3],
             [2,1]])
lambda1, v2 = np.linalg.eig(B)
print(lambda1) #고윳값
print(v2) #고유벡터 

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [27]:
#2. 
A = np.array([[1, -2],
             [2, -3]])
lambdaA, v = np.linalg.eig(A)

print(lambdaA)
print(v)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [30]:
#3. 
B = np.array([[2,3],
             [2,1]])
lmB, v = np.linalg.eig(B)

print(lmB) #고윳값
print(v) #고유벡터

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [32]:
#4. 
C = np.array([[0, -1],
             [1,0]])
lmC, v = np.linalg.eig(C)

print(lmC) #복소수 고윳값
print(v) #복소수 고유벡터

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


In [34]:
#5. 
D = np.array([[2,1],
             [1,2]])
lmD, v = np.linalg.eig(D)


print(lmD) #고윳값
print(v) #고유벡터

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [40]:
#6. 
E = np.array([[2,3],
             [2,1]])
lmE, v = np.linalg.eig(E)

print('#6')
print(lmE)
print(v)
print()

#7. 
F = np.array([[1,1],
             [0,1]])

lmF, v = np.linalg.eig(F)

print('#7')
print(lmF) #중복고윳값
print(v) #중복 고유벡터, 미세하게 다른 값 나왔다. 

#6
[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]

#7
[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


In [82]:
I = np.eye(2) #항등행렬
LI, V = np.linalg.eig(I)


print(LI) #중복고윳값
print()
print(V) #고유벡터

v1 = np.array([V[0][0],
               V[1][0]])
v2 = np.array([V[0][1], 
               V[1][1]])

v = np.vstack([v1, v2]).T
c = np.array([1,8])

result = v@c
result

[1. 1.]

[[1. 0.]
 [0. 1.]]


array([1., 8.])

In [84]:
I@result == 1*result # 중복고윳값의 서로 다른 고유벡터 선형조합한 결과물은 그 중복고윳값의 또 다른 고유벡터다. 

array([ True,  True])

# 행렬의 대각화 : 특정 행렬을 그 행렬의 고유벡터행렬과 고윳값 행렬 이용해서 나타낸 것
$B = V*\lambda*V^{-1}$

In [87]:
B = np.array([[2,3],
             [2,1]])
lambda1, v = np.linalg.eig(B) #고유분해

print(lambda1)
print(v)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [108]:
v1 = np.array([v[0][0], v[1][0]])
v2 = np.array([v[0][1], v[1][1]])

V = np.vstack([v1,v2]).T #고유벡터 행렬
ld = np.diag([4, -1]) #고윳값 행렬

# 고유벡터 행렬 역행렬 존재하는지 보자. 
print('역행렬 유무 : %s' %np.linalg.det(v)) #역행렬 있다

V_INV = np.linalg.inv(v) #고유벡터행렬의 역행렬

역행렬 유무 : 0.9805806756909202


In [112]:
B #

array([[2, 3],
       [2, 1]])

In [113]:
v@ld@V_INV #대각화된 행렬 B

array([[2., 3.],
       [2., 1.]])

In [122]:
# 3.3.7 연습문제 
Z = np.array([[1, 1],
             [0, 1]])
ld, v = np.linalg.eig(Z)
print(ld)

print(v)

#고유벡터행렬 역행렬이 존재해야만 행렬 대각화 할 수 있다.  == 행렬 대각화 전제조건은 고유벡터행렬 V 역행렬 존재하는거다. 
np.linalg.inv(v) # v 계산에 수치 오류가 있어서 정확하지 않은 결과 나오는 듯. 

[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


array([[1.00000000e+00, 4.50359963e+15],
       [0.00000000e+00, 4.50359963e+15]])

In [125]:
np.linalg.matrix_rank(v) #랭크가 풀랭크가 아니다 == 역행렬이 없다

1

In [165]:
# 3.3.8 연습문제 
A = np.array([[2,3],
             [2,1]])

V = np.array([[3/np.sqrt(13), -1/np.sqrt(2)],
             [2/np.sqrt(13), 1/np.sqrt(2)]]) #고유벡터행렬

LM = np.diag([4, -1]) #고윳값행렬

#고유벡터 행렬이 풀랭크인가?(=역행렬 존재하는가?)
print('랭크(풀랭크=2) : %s' %np.linalg.matrix_rank(V)) #역행렬 존재한다(=풀랭크다)
print('풀랭크')

np.linalg

랭크(풀랭크=2) : 2
풀랭크


<module 'numpy.linalg' from '/Users/kibeomkim/opt/anaconda3/lib/python3.8/site-packages/numpy/linalg/__init__.py'>

In [167]:
np.linalg.inv(A)

array([[-0.25,  0.75],
       [ 0.5 , -0.5 ]])

In [168]:
V@np.linalg.inv(LM)@np.linalg.inv(V)

array([[-0.25,  0.75],
       [ 0.5 , -0.5 ]])

In [177]:
#손으로 계산한 결과랑 비교해보자. 
V_INV = np.array([[np.sqrt(13)/5, np.sqrt(13)/5],
         [(-2*np.sqrt(2))/5, (3*np.sqrt(2))/5]])
L_INV = np.array([[1/4,0],
                 [0,-1]])
V@L_INV@V_INV

array([[-0.25,  0.75],
       [ 0.5 , -0.5 ]])

In [193]:
A = np.array([[60,30,20],
             [30,20,15],
             [20,15,12]])

L, V = np.linalg.eig(A)

print(L)
print()
print(V)

L1 = L[0]
L2 = L[1]
L3 = L[2]

v1 = V[:,[0]]
v2 = V[:,[1]]
v3 = V[:,[2]]

A1 = v1@v1.T
A2 = v2@v2.T
A3 = v3@v3.T

[84.49913563  7.33962395  0.16124042]

[[ 0.82704493  0.54744843  0.12765933]
 [ 0.4598639  -0.52829024 -0.71374689]
 [ 0.32329844 -0.64900666  0.68867153]]


In [195]:
#첫번째 랭크-1 행렬
L1*A1

array([[57.79768857, 32.13739648, 22.59357583],
       [32.13739648, 17.8694387 , 12.56276371],
       [22.59357583, 12.56276371,  8.83200836]])

In [196]:
#두번째 랭크-1 행렬
L2*A2

array([[ 2.19968372, -2.12270483, -2.60775134],
       [-2.12270483,  2.04841985,  2.51649195],
       [-2.60775134,  2.51649195,  3.09152039]])

In [197]:
#세번째 랭크-1행렬
L3*A3

array([[ 0.00262772, -0.01469165,  0.01417551],
       [-0.01469165,  0.08214145, -0.07925566],
       [ 0.01417551, -0.07925566,  0.07647125]])

In [198]:
(L1*A1)+(L2*A2)+(L3*A3)

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

In [199]:
A

array([[60, 30, 20],
       [30, 20, 15],
       [20, 15, 12]])

In [200]:
# 실수로 구성된 대칭행렬 A 역행렬을 랭크-1행렬합으로 표현하기 
#1. 
1/L1*A1

array([[0.0080948 , 0.00450097, 0.00316432],
       [0.00450097, 0.00250269, 0.00175947],
       [0.00316432, 0.00175947, 0.00123696]])

In [201]:
1/L2/A2

array([[ 0.45461081, -0.47109706, -0.38347215],
       [-0.47109706,  0.48818117,  0.39737858],
       [-0.38347215,  0.39737858,  0.32346544]])

In [202]:
1/L3/A3

array([[380.55808746, -68.06585267,  70.54421178],
       [-68.06585267,  12.17412125, -12.61739557],
       [ 70.54421178, -12.61739557,  13.07681003]])

In [203]:
(1/L1*A1)+(1/L2*A2)+(1/L3*A3)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [204]:
np.linalg.inv(A)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

$X^TX$ 
- 분산행렬(대칭행렬, 정방행렬)

In [216]:
# 3.3.9 연습문제
#1. 
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data #붓꽃 특징행렬

#특징행렬의 분산행렬 구하자
V_ = X.T@X
V_
#분산행렬의 고윳값 구하자
#고유분해 
LAM, V = np.linalg.eig(V_)

print('분산행렬 고윳값 : %s' %LAM)
print()
#print(V)

분산행렬 고윳값 : [9.20830507e+03 3.15454317e+02 1.19780429e+01 3.55257020e+00]



In [233]:
#2. 
from sklearn.datasets import load_boston
boston = load_boston()
X1 = boston.data #보스턴 집값 특징행렬

#특징행렬의 분산행렬 
V_2 = X1.T@X1
print(V_2)
print()
print()
#분산행렬의 고윳값
lam2, V = np.linalg.eig(V_2)
print(lam2)

[[4.39703436e+04 4.68702660e+02 3.24790952e+04 6.48084600e+01
  1.22612317e+03 1.08219511e+04 1.68514980e+05 3.46627456e+03
  4.11186651e+04 1.17307321e+06 3.64715518e+04 4.99455291e+05
  3.72684187e+04]
 [4.68702660e+02 3.40029000e+05 2.09030900e+04 2.70000000e+02
  2.48444175e+03 3.87184670e+04 2.05485400e+05 3.82992940e+04
  2.29180000e+04 1.72295450e+06 9.61321500e+04 2.23960499e+06
  3.80196800e+04]
 [3.24790952e+04 2.09030900e+04 8.65256299e+04 4.45170000e+02
  3.43239536e+03 3.44618165e+04 4.49313490e+05 1.62206733e+04
  7.17656500e+04 2.72134904e+06 1.06875320e+05 1.89702529e+06
  8.62407050e+04]
 [6.48084600e+01 2.70000000e+02 4.45170000e+02 3.50000000e+01
  2.07699000e+01 2.28186000e+02 2.71250000e+03 1.06039800e+02
  3.26000000e+02 1.35190000e+04 6.12200000e+02 1.30549100e+04
  3.93460000e+02]
 [1.22612317e+03 2.48444175e+03 3.43239536e+03 2.07699000e+01
  1.62470380e+02 1.75151941e+03 2.04522016e+04 9.70389866e+02
  2.99183590e+03 1.21170623e+05 5.20395546e+03 9.80793458e+0